### ISSUE TITLE
Перевод

### ISSUE THREAD

**Issue by Niklex21** [Kvisaz/nukecaravan#3]
Привет! Код красота, читать одно удовольствие. Но появился один вопрос. Почему Ox переводится как брамин? Ведь брамин это не средство передвижения и не животное...

**Comment by findoff** [comment]
Привет, потому что http://fallout.wikia.com/wiki/Brahmin (=

**Comment by Niklex21** [comment]
Понял, все ок 😊

Sent from Mail for Windows 10
